### ISSUE TITLE
[System Support] DnD 5e 3.3.1 no longer working with REDY 1.5.0

### ISSUE THREAD

**Issue by ravingdragoon** [ChasarooniZ/PF2e-Reactive-Token-Ring#45]
With the latest update, REDY no longer works with DnD 5e 3.3.1. I now get the errors below and the canvas fails to load on any scene.

```
Error: Failed drawing interface canvas group: Cannot read properties of undefined (reading 'members'). Cannot read properties of undefined (reading 'members')
[Detected 3 packages: pf2e-reactive-token-ring(1.5.0), lib-wrapper(1.12.15.0), system:dnd5e(3.3.1)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Hooks.onError#lib-wrapper (listeners.js:140:11)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:187:52)
    at #draw (foundry.js:25053:15)
    at async Canvas.draw (foundry.js:24937:5)
    at async Scene.view (foundry.js:21358:7)
    at async Game.initializeCanvas (foundry.js:9270:20)
    at async Game.setupGame (foundry.js:9094:5)
    at async Game._initializeGameView (foundry.js:10431:5)
    at async Game.initialize (foundry.js:8994:5)Caused by: TypeError: Failed drawing interface canvas group: Cannot read properties of undefined (reading 'members'). Cannot read properties of undefined (reading 'members')
[Detected 3 packages: pf2e-reactive-token-ring(1.5.0), lib-wrapper(1.12.15.0), system:dnd5e(3.3.1)]
    at getSetting (autoColorRing.js:93:37)
    at Token5e.autoColorRing (autoColorRing.js:7:23)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:591:14)
    at 🎁CONFIG.Token.objectClass.prototype.getRingColors#0 (libWrapper-wrapper.js:189:20)
    at TokenRing.configureVisuals (foundry-esm.js:60031:72)
    at TokenRing.configure (foundry-esm.js:59957:12)
    at #initializeRing (foundry.js:58946:18)
    at Token5e._draw (foundry.js:59573:25)
    at async Token5e._draw (token.mjs:37:5)
    at async foundry.js:26710:7
    at async Promise.all (index 0)
    at async TokenLayer._draw (foundry.js:34300:5)
    at async TokenLayer._draw (foundry.js:41582:5)
    at async foundry.js:33712:7
    at async InterfaceCanvasGroup._draw (foundry.js:28263:9)
    at async InterfaceCanvasGroup._draw (foundry.js:50656:5)
    at async foundry.js:28247:9
    at async #draw (foundry.js:25051:9)
    at async Canvas.draw (foundry.js:24937:5)
    at async Scene.view (foundry.js:21358:7)
    at async Game.initializeCanvas (foundry.js:9270:20)
    at async Game.setupGame (foundry.js:9094:5)
    at async Game._initializeGameView (foundry.js:10431:5)
    at async Game.initialize (foundry.js:8994:5)
```
```
Failed drawing interface canvas group: Cannot read properties of undefined (reading 'members') | foundry.js:72040
  | fetch | @ | foundry.js:72040
  | notify | @ | foundry.js:71936
  | error | @ | foundry.js:71973
  | onError | @ | foundry.js:656
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:507
  | 🎁Hooks.onError#lib-wrapper | @ | listeners.js:140
  | 🎁Hooks.onError#0 | @ | libWrapper-wrapper.js:187
  | #draw | @ | foundry.js:25053
  | Promise.finally |   |  
  | draw | @ | foundry.js:24936
  | view | @ | foundry.js:21358
  | initializeCanvas | @ | foundry.js:9270
  | await in initializeCanvas |   |  
  | setupGame | @ | foundry.js:9081
  | await in setupGame |   |  
  | _initializeGameView | @ | foundry.js:10431
  | _initializeView | @ | foundry.js:10407
  | initialize | @ | foundry.js:8994
  | await in initialize |   |  
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:507
  | 🎁libWrapperInit | @ | libWrapper-api.js:805
  | await in 🎁libWrapperInit |   |  
  | 🎁Game.prototype.initialize#0 | @ | libWrapper-wrapper.js:187
  | window.addEventListener.once | @ | foundry.js:95938
```

**Comment by ChasarooniZ** [comment]
DnD was never a supported system as it has its own built in Dynamic Handling?

**Comment by ravingdragoon** [comment]
Apologies, I installed it based on the recommendation from SETT.
